{% set name = "rinohtype" %}
{% set version = "0.5.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rinohtype-{{ version }}.tar.gz
  sha256: 2efc38b5f41541693617e5a4bc6826e8932897d3c14b1b0ecd3ae4aaff404224

build:
  entry_points:
    - rinoh = rinoh.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.8
    - pip
  run:
    - python >=3.8
    - appdirs >=1.4.3,<2.0.0
    - docutils >=0.15
    - importlib-metadata >=0.21
    - packaging >=14.0
    - recommonmark >=0.6.0
    - sphinx >=2.2.1
  run_constrained:
    - sphinx >=2.2.1

test:
  imports:
    - rinoh
  commands:
    - rinoh --help
  requires:
    - pip

about:
  home: https://github.com/brechtm/rinohtype
  summary: The Python document processor
  license: AGPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mediocretech
